on:
  push:
    branches:    
      - 'master'

jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
 
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.x
 
    - name: Test
      working-directory: ./src/Purgomalum.Test
      run: dotnet test